### ISSUE TITLE
files and folders from upstream

### ISSUE THREAD

**Issue by epidrome** [ioniodi/minimal-ionio#2]
@nickgarlis do you have to keep all files to make this work? i think it is enough to keep the modified files

**Comment by nickgarlis** [comment]
@epidrome It depends on which files you are referring to. We could get rid of some directories consisting of yml files such as `_data` but we should definitely keep everything that's code related.

**Comment by epidrome** [comment]
Isn't there any way to define the upstream gem as a theme dependency?

**Comment by epidrome** [comment]
/remind me about theme dependencies in 6 months

**Comment by epidrome** [comment]
it seems this is still an [open issue at jekyll-remote-theme](https://github.com/benbalter/jekyll-remote-theme/issues/35)

**Comment by epidrome** [comment]
marked as `help wanted` :confused:

**Comment by epidrome** [comment]
at last, there is a pending PR that adds theme inheritance: https://github.com/jekyll/jekyll/pull/7554

**Comment by epidrome** [comment]
@jimDragon 

ορισμένες γενικές συζητήσεις καλύτερα να γίνονται εδώ παρά στο αίτημα #22 

η τεκμηρίωση καλύτερα να μπει στο γουίκι εδώ

**Comment by epidrome** [comment]
@jimDragon 

μην σε φοβίζουν οι αλλαγές στο αρχικό, δεν είναι ανάγκη να είμαστε 100% επίκαιροι, 

έτσι και αλλιώς θα το χάσουμε πάλι καθώς θα αλλάζει

αν θες γράψου εδώ ώστε να έχουμε την ενημέρωση αν/όταν βγει: https://github.com/jekyll/jekyll/pull/7554

**Comment by jimDragon** [comment]
> έτσι και αλλιώς θα το χάσουμε πάλι καθώς θα αλλάζει

Θα καθυστερήσει πολύ από οτι φαίνεται... Άρα εγώ τι κάνω; Απλά περιμένω τα reviews  στο PR μου. σωστά;

**Comment by epidrome** [comment]
ναι, για την ώρα, και για πολλούς μήνες ακόμη, το αίτημα σου είναι ότι καλύτερο έχουμε!

**Comment by epidrome** [comment]
@jimDragon αν θες να βάλεις στο γουικι τις (συντομες) οδηγίες για αναβάθμιση, υποθέτω κάποιο κοπι-πειστ-εντιτ από το σχόλιο σου στο αντίστοιχο αίτημα
