### ISSUE TITLE
Αδυναμία ευρεσης των αλλαγών μου όταν πάω να κάνω pull request

### ISSUE THREAD

**Issue by AsteriosP** [ioniodi/minimal-ionio#20]
@epidrome @GIANNIS-AGGELIS 
μετά το revert που έγινε, στο pull request δεν αναγνωρίζονται οι αλλαγες που έχω κάνει στα αρχεία.

π.χ. 
το δικό μου αρχείο είναι [αυτό](https://github.com/AsteriosP/minimal-ionio/blob/footer_rendering/_includes/footer/custom.html) και το αρχείο που βρίσκεται στο minimal-ionio είναι [αυτό](https://github.com/ioniodi/minimal-ionio/blob/master/_includes/footer/custom.html)

**Comment by constantinexisc** [comment]
Ειναι λιγο παραξενη η περιπτωση η συγκεκριμενη γιατι τα commits σου δεν εχουν χαθει, υπαρχουν στο ιστορικο του branch (master) που πας να κανεις merge παλι με το pull request απλα εχουν γινει revert με ενα μεταγενεστερο commit. Aν πας να κανεις pull request απο το κλαδι σου που εγινε προηγουμενως merge και μετα revert τοτε το github θα σου πει οτι βρισκεσαι "πισω" απο το κλαδι προς το οποιο πας να κανεις pull request, αρα δεν θα σου δειχνει τις αλλαγες που λες ακομα και αν ειναι διαφορετικα τα αρχεια.

Δεν ξερω αν εκανα κατανοητο τι θελω να πω, γιατι χωρις σχηματα η κατασταση ειναι λιγο δυσκολο να εξηγηθει.

Για λυση τωρα θα πρεπει να μου απαντησεις να δουμε αν οντως και εσυ πιστευεις οτι αυτο γινεται και βλεπουμε απο εκει.
