### ISSUE TITLE
Issue while Building for deployment

### ISSUE THREAD

**Issue by NikosAvg** [ioniodi/minimal-ionio#25]
Η παρακάτω γραμμή   
https://github.com/ioniodi/minimal-ionio/blob/21b766e02f3898a5b1cd4f63d4e938fc3ccf0894/_includes/book.html#L6

δημιούργησε το εξής σφάλμα κατά το deployment μου.

Liquid Exception: Liquid syntax error (/tmp/jekyll-remote-theme-20200507-1275-89ovsa/_includes/book.html line 6): Unknown tag 'details_link' included in /_layouts/courses.html

**Comment by p15zerv** [comment]
Τα συγκεκριμένα tags τα προσθέτει το jekyll-scholar. Είναι εγκατεστημένο τοπικά; Δοκίμασε ένα bundle install.

**Comment by NikosAvg** [comment]
Οχι το χρησιμοποιώ ως remote theme , σου έκανε κανονικά build εσενα;

**Comment by p15zerv** [comment]
Μήπως δεν έχεις κάνει update με το upstream? Νομίζω χρειάζεται να έχεις το _layouts/bibtex.html για να μπορεί το jekyll-scholar να βγάλει τις σελίδες από τα βιβλία.

**Comment by NikosAvg** [comment]
Δεν χρησιμοποει δικο μου αποθετηριο σαν remote theme το κεντρικο χρησιμοποιω εγινε αλλαγη και στο site-gr;

**Comment by p15zerv** [comment]
Ναι στο site-gr υπάρχει το συγκεκριμένο layout, οπότε δοκίμασε ένα update.

**Comment by NikosAvg** [comment]
Οκ ευχαριστω.
